config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  #resources :articles, only: [:show, :index, :new, :create, :edit, :update, destroy]
  #or
  resources :articles do
     resources :comments, only: [:show, :index, :new, :create, :destroy] 
  end

  get "signup", to: "users#new"

  #post 'users', to: 'users#create' this was needed to avoid that path error
  resources :users, except: [:new]
  get '/auth/:provider/callback', to: 'sessions#omniauth'  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  
  resources :categories




end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
	 
    has_many :article_categories, dependent: :destroy 
    has_many :categories, through: :article_categories
	 
	 has_many :comments, dependent: :destroy
    
    validates :title , presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}

	 scope :user_article_count, lambda {|user_id| where("user_id = ?", user_id).select(:user_id).uniq }
     accepts_nested_attributes_for :categories          
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  
  end

  def index
    
    @articles = Article.paginate(page: params[:page], per_page: 3)
  
  end

  def new
    
    @article = Article.new
  
  end

  def edit
  
  end

  def create
   
    if !article_params["categories_attributes"].nil? &&
        article_params["categories_attributes"]["0"]["name"].empty?
        params[:article].delete :categories_attributes
    end
      @article = Article.new(article_params)
         @article.user = current_user
          if @article.save
              flash[:notice] = "Article was created OK"
              redirect_to article_path(@article)
            else
            render "new"
          end
       end

  def update
    
    if !article_params["categories_attributes"].nil? &&
      article_params["categories_attributes"]["0"]["name"].empty?
      params[:article].delete :categories_attributes
    end
  
          if @article.update(article_params)
      
           flash[:notice] = "Article was updated OK"
      
            redirect_to article_path(@article)
  
              else
      
                render "edit"
    
          end
    end

  def destroy
  
     @article.destroy
    
        redirect_to articles_path
     
   end

  private

  def set_article
    if Article.exists?(params[:id])
	      
        @article = Article.find(params[:id])
	  
      else
	        
        flash[:error] = "No such article " + params[:id]
        
      redirect_to articles_path
 	      
    end
  end

  def article_params

    params.require(:article).permit(:title, :description, category_ids: [], categories_attributes: [:id, :name])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/views/articles/_article.html.erb
 

<table>

<thead>

<tr>

<th> Title </th>

<th> Description </th>

<th> Article by </th>

<th colspan = "3" > Actions </th>

<th colspan = "3" > Categories </th>

 

</tr>

</thead>

<tbody>

<% @articles.each do |article| %>

<tr>

<td><%= article.title %></td>

<td><%= article.description %></td>

<td><%= link_to article.user.username, user_path(article.user) %></td>

<td><%= link_to "Show", article_path(article.id) %></td>

<% if logged_in? && (article.user == current_user || current_user.admin?) %>

   <td><%= link_to "Edit", edit_article_path(article.id) %></td>

   <td><%= button_to "Delete", { action: "destroy", id: article.id},  method: :delete, data: { confirm: "Are you sure?" } %></td>

<%else %>

   <td> </td>

   <td> </td>  

<% end %>

 

<p>

<td>

          <% if article.categories.any? %>

            <div><%= render article.categories %></div>

          <% end %>

</td>                     

</p>

 

</tr>

<% end %>

</tbody>

 

</table>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<%= form_with(model: @article, local: true) do |f| %>

<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.label :category %><br>
  <%= f.collection_select(:category_ids, Category.all, :id, :name,
     { prompt: "Please choose from the list below "}, { multiple: true, size: 5 }) %>
</p>
 

<% if current_user.admin? %>

<br>

    <p>Or Create a New Category:</p>

    <%= f.fields_for :categories, Category.new do |category_attributes|%>

        <%= category_attributes.label :name, "Category Name:" %>

        <%= category_attributes.text_field :name %>

    <% end %> 

<br>

<% end %>

<br>
<p>
 <%= f.submit %><br>
 </p>

<% end %>

app/views/articles/edit.html.erb
<h1> Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and Return to Articles', articles_path %> 

app/views/articles/index.html.erb
<h1>Historical Oracle Articles </h1>

<% if false %>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<% end %>

<%= render 'article' %>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<br>

<%= link_to 'Create New Article', new_article_path %>



  

app/views/articles/new.html.erb
<h1> Create A New Article</h1>

<%= render 'form' %>

<%= link_to 'Return to Articles', articles_path %> 

app/views/articles/show.html.erb
<h1>Showing Article Details</h1>

<p><strong> Title: </strong><%= @article.title %></p>
<p><strong> Description: </strong><%= @article.description %></p>
<p><strong> Article by : </strong><%= link_to @article.user.username, user_path(@article.user) if @article.user %></p>

<p>
          <% if @article.categories.any? %>
            <div><strong> Categories: </strong><%= render @article.categories %></div> 
          <% end %>
</p>
<p>
          <% if @article.comments.any? %>
            <div><strong> Comments: </strong><%= link_to "View Comments", article_comments_path(@article) %></div> 
          <% end %>
</p>

<table>

<tr>

<td>

<%= link_to "Add Comment", new_article_comment_path(@article) %> |

</td>

<% if logged_in? && (@article.user == current_user || current_user.admin?) %>

<td>

   <%= link_to "Edit", edit_article_path(@article) %>

</td>

<td>

   <%= button_to "Delete", { action: "destroy", id: @article.id},  method: :delete, data: { confirm: "Are you sure?" } %>

</td>

<% end %>

<td>

<%= link_to "Return to Articles", articles_path %>

</td>

</tr>

</table>