config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  #resources :articles, only: [:show, :index, :new, :create, :edit, :update, destroy]
  #or
  resources :articles do
     resources :comments, only: [:show, :index, :new, :create, :destroy] 
  end

  get "signup", to: "users#new"

  #post 'users', to: 'users#create' this was needed to avoid that path error
  resources :users, except: [:new]
  get '/auth/:provider/callback', to: 'sessions#omniauth'  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  
  resources :categories




end

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
    <%= msg %>
    <% end %>

app/views/layouts/_navigation.html.erb
<div class="topnav" id="myTopnav">
<a href="#home" class="active"><%= link_to "Home", root_path %> </a>
<a href="#users"> <%= link_to "Users", users_path %></a>
<div class="dropdown">
  <button class="dropbtn">Articles 
    <i class="fa fa-caret-down"></i>
  </button>
  <div class="dropdown-content">
    <% if logged_in? %>
       <a href="#"><%= link_to "Create new article", new_article_path %></a>   
    <% end %>    
    <a href="#"><%= link_to "View articles", articles_path %></a>
  </div>
</div>
<div class="dropdown">
  <button class="dropbtn">Categories 
    <i class="fa fa-caret-down"></i>
  </button>
  <div class="dropdown-content">
    <% if logged_in?  && current_user.admin? %>
       <a href="#"><%= link_to "Create new category", new_category_path %></a>   
    <% end %>    
    <a href="#"><%= link_to "View categories", categories_path %></a>
  </div>
</div> 
 
<% if logged_in? %>
    <a href="#login"> <%= link_to current_user.username, user_path(current_user) %></a>

   <div class="dropdown">
      <button class="dropbtn"> <%= "Admin" if current_user.admin? %>  Profile [<%= current_user.username %>] 
       <i class="fa fa-caret-down"></i>
      </button>
     <div class="dropdown-content">
       <%= link_to "View your profile", user_path(current_user) %>
       <%= link_to "Edit your profile", edit_user_path(current_user) %>
       <%= button_to "Delete your profile", { action: "destroy", id: current_user.id},  method: :delete, data: { confirm: "Are you sure you want to delete the user account and all associated articles?" } %>                  
    </div>
   </div>

    <a href="#logout"> <%= link_to "Logout", logout_path, method: :delete %></a>
 <% else %>
    <a href="#login"><%= link_to "LogIn", login_path %></a> 
    <a href="#signup"><%= link_to "SignUp", signup_path %></a> 
 <% end %>
  <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
</div>

<script>
function myFunction() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HistoricalOracle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    

 <style>
body {margin:0;font-family:Arial}

.topnav {
  overflow: hidden;
  background-color: #FF6347
}



.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.active {
  background-color:#FF6347;
  color: gold;
}

.topnav .icon {
  display: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 17px;    
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.topnav a:hover, .dropdown:hover .dropbtn {
  background-color: #555;
  color: white;
}

.dropdown-content a:hover {
  background-color: #ddd;
  color: black;
}

.dropdown:hover .dropdown-content {
  display: block;
}

@media screen and (max-width: 600px) {
  .topnav a:not(:first-child), .dropdown .dropbtn {
    display: none;
  }
  .topnav a.icon {
    float: right;
    display: block;
  }
}

@media screen and (max-width: 600px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;
  }
  .topnav.responsive a {
    float: none;
    display: block;
    text-align: left;
  }
  .topnav.responsive .dropdown {float: none;}
  .topnav.responsive .dropdown-content {position: relative;}
  .topnav.responsive .dropdown .dropbtn {
    display: block;
    width: 100%;
    text-align: left;
  }
}


table, th, td {

  border: 1px solid black;

  border-collapse: collapse;

}

th, td {

  padding: 5px;

}
</style>
  
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>  
    <%= yield %>
  </body>
</html>